"""crear tabla perfiles_veterinarios

Revision ID: 4aa7480f5000
Revises: a574e2c295d6
Create Date: 2026-09-13 11:46:14.982032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4aa7480f5000'
down_revision: Union[str, Sequence[str], None] = 'a574e2c295d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('knowledge_vectors')
    op.drop_table('pet_vectors')
    op.drop_index(op.f('idx_escaneos_fecha'), table_name='escaneos')
    op.drop_index(op.f('idx_escaneos_qr'), table_name='escaneos')
    op.drop_table('escaneos')
    op.alter_column('codigos_qr', 'codigo',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('codigos_qr', 'activo',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('codigos_qr', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('codigos_qr_codigo_key'), 'codigos_qr', type_='unique')
    op.drop_index(op.f('idx_qr_codigo'), table_name='codigos_qr')
    op.drop_index(op.f('idx_qr_mascota'), table_name='codigos_qr')
    op.create_index(op.f('ix_codigos_qr_codigo'), 'codigos_qr', ['codigo'], unique=True)
    op.alter_column('mascotas', 'usuario_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('mascotas', 'nombre',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('mascotas', 'edad_aproximada',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('mascotas', 'foto_url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('mascotas', 'estado',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               nullable=False,
               existing_server_default=sa.text("'en_casa'::character varying"))
    op.alter_column('mascotas', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('mascotas', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_mascotas_usuario'), table_name='mascotas')
    op.drop_constraint(op.f('mascotas_usuario_id_fkey'), 'mascotas', type_='foreignkey')
    op.create_foreign_key(None, 'mascotas', 'usuarios', ['usuario_id'], ['id'])
    op.alter_column('usuarios', 'nombre',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('usuarios', 'telefono',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('usuarios', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('usuarios', 'rol',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'usuario'::character varying"))
    op.alter_column('usuarios', 'avatar_url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('usuarios', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_usuarios_email'), table_name='usuarios')
    op.drop_constraint(op.f('usuarios_email_key'), 'usuarios', type_='unique')
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.drop_column('usuarios', 'updated_at')
    op.drop_column('usuarios', 'provider_id')
    op.drop_column('usuarios', 'provider')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('provider', sa.VARCHAR(length=50), server_default=sa.text("'credentials'::character varying"), autoincrement=False, nullable=True))
    op.add_column('usuarios', sa.Column('provider_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('usuarios', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.create_unique_constraint(op.f('usuarios_email_key'), 'usuarios', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_usuarios_email'), 'usuarios', ['email'], unique=False)
    op.alter_column('usuarios', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('usuarios', 'avatar_url',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('usuarios', 'rol',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'usuario'::character varying"))
    op.alter_column('usuarios', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('usuarios', 'telefono',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('usuarios', 'nombre',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_constraint(None, 'mascotas', type_='foreignkey')
    op.create_foreign_key(op.f('mascotas_usuario_id_fkey'), 'mascotas', 'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_mascotas_usuario'), 'mascotas', ['usuario_id'], unique=False)
    op.alter_column('mascotas', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('mascotas', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('mascotas', 'estado',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'en_casa'::character varying"))
    op.alter_column('mascotas', 'foto_url',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('mascotas', 'edad_aproximada',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('mascotas', 'nombre',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('mascotas', 'usuario_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_codigos_qr_codigo'), table_name='codigos_qr')
    op.create_index(op.f('idx_qr_mascota'), 'codigos_qr', ['mascota_id'], unique=False)
    op.create_index(op.f('idx_qr_codigo'), 'codigos_qr', ['codigo'], unique=False)
    op.create_unique_constraint(op.f('codigos_qr_codigo_key'), 'codigos_qr', ['codigo'], postgresql_nulls_not_distinct=False)
    op.alter_column('codigos_qr', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('codigos_qr', 'activo',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('codigos_qr', 'codigo',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.create_table('escaneos',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('qr_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('latitud', sa.NUMERIC(precision=10, scale=8), autoincrement=False, nullable=True),
    sa.Column('longitud', sa.NUMERIC(precision=11, scale=8), autoincrement=False, nullable=True),
    sa.Column('direccion_aproximada', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('mensaje_encontrador', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('telefono_encontrador', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['qr_id'], ['codigos_qr.id'], name=op.f('escaneos_qr_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('escaneos_pkey'))
    )
    op.create_index(op.f('idx_escaneos_qr'), 'escaneos', ['qr_id'], unique=False)
    op.create_index(op.f('idx_escaneos_fecha'), 'escaneos', [sa.literal_column('created_at DESC')], unique=False)
    op.create_table('pet_vectors',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('pet_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('document', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=3072), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['pet_id'], ['mascotas.id'], name=op.f('pet_vectors_pet_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pet_vectors_pkey')),
    sa.UniqueConstraint('pet_id', name=op.f('pet_vectors_pet_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('knowledge_vectors',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('doc_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('titulo', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('contenido', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('categoria', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=3072), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('knowledge_vectors_pkey'))
    )
    # ### end Alembic commands ###
