'use client'

import { FormEvent, useEffect, useState } from 'react'
import Link from 'next/link'
import { Calendar, FileText, PawPrint, Plus, Search, Users } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Badge } from '@/components/ui/badge'
import { veterinarioApi, asItems, formatDateOnly, formatTime, parseApiError, today, toIso, type HistoriaClinica, type Turno } from '@/lib/api/veterinario'
import type { Pet } from '@/lib/types'

type UserRecord = { id: string; nombre: string; email: string; rol?: string }

function Shell({ title, description, children }: { title: string; description: string; children: React.ReactNode }) {
  return <section className="flex flex-col gap-6"><header><h1 className="text-2xl font-bold tracking-tight">{title}</h1><p className="text-sm text-muted-foreground leading-6">{description}</p></header>{children}</section>
}
function ErrorMessage({ error }: { error: string }) { return error ? <p role="alert" className="text-sm text-destructive">{error}</p> : null }

export function VeterinarianAppointments() {
  const [date, setDate] = useState(today()); const [turnos, setTurnos] = useState<Turno[]>([]); const [error, setError] = useState(''); const [saving, setSaving] = useState(false)
  const [form, setForm] = useState({ mascota_id: '', fecha_hora_inicio: '', fecha_hora_fin: '', tipo_servicio: 'Consulta general', observaciones: '' })
  const load = async () => { try { setError(''); setTurnos(await veterinarioApi.agenda(date)) } catch (e) { setError(parseApiError(e)) } }
  useEffect(() => { load() }, [date])
  const submit = async (event: FormEvent) => { event.preventDefault(); setSaving(true); try { await veterinarioApi.crearTurno({ ...form, fecha_hora_inicio: toIso(form.fecha_hora_inicio), fecha_hora_fin: toIso(form.fecha_hora_fin) }); setForm({ mascota_id: '', fecha_hora_inicio: '', fecha_hora_fin: '', tipo_servicio: 'Consulta general', observaciones: '' }); await load() } catch (e) { setError(parseApiError(e)) } finally { setSaving(false) } }
  return <Shell title="Turnos" description="Agenda y administra las consultas de tu clínica."><div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_360px]"><Card><CardHeader><CardTitle className="flex items-center gap-2"><Calendar data-icon="inline-start" /> Agenda del día</CardTitle><Input type="date" value={date} onChange={e => setDate(e.target.value)} /></CardHeader><CardContent className="flex flex-col gap-3"><ErrorMessage error={error} />{turnos.length ? turnos.map(t => <div key={t.id} className="flex flex-col gap-2 rounded-lg border p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-medium">{t.tipo_servicio}</p><p className="text-sm text-muted-foreground">Mascota: {t.mascota_id}</p><p className="text-sm text-muted-foreground">{formatTime(t.fecha_hora_inicio)} - {formatTime(t.fecha_hora_fin)}</p></div><Badge variant={t.estado === 'CANCELADO' ? 'destructive' : 'secondary'}>{t.estado}</Badge></div>) : <p className="text-sm text-muted-foreground">No hay turnos para esta fecha.</p>}</CardContent></Card><Card><CardHeader><CardTitle>Nuevo turno</CardTitle></CardHeader><CardContent><form onSubmit={submit} className="flex flex-col gap-4"><Field label="ID de mascota"><Input required value={form.mascota_id} onChange={e => setForm({ ...form, mascota_id: e.target.value })} /></Field><Field label="Inicio"><Input required type="datetime-local" value={form.fecha_hora_inicio} onChange={e => setForm({ ...form, fecha_hora_inicio: e.target.value })} /></Field><Field label="Fin"><Input required type="datetime-local" value={form.fecha_hora_fin} onChange={e => setForm({ ...form, fecha_hora_fin: e.target.value })} /></Field><Field label="Servicio"><Input required value={form.tipo_servicio} onChange={e => setForm({ ...form, tipo_servicio: e.target.value })} /></Field><Button disabled={saving} type="submit"><Plus data-icon="inline-start" />{saving ? 'Guardando…' : 'Agendar turno'}</Button></form></CardContent></Card></div></Shell>
}

export function VeterinarianPets() { const [pets, setPets] = useState<Pet[]>([]); const [error, setError] = useState(''); useEffect(() => { veterinarioApi.mascotas().then(data => setPets(asItems<Pet>(data))).catch(e => setError(parseApiError(e))) }, []); return <Shell title="Mascotas" description="Consulta las mascotas disponibles para atención clínica."><Card><CardContent className="flex flex-col gap-3 p-4"><ErrorMessage error={error} />{pets.length ? pets.map(p => <div key={p.id} className="flex items-center justify-between rounded-lg border p-4"><div className="flex items-center gap-3"><PawPrint className="text-primary" /><div><p className="font-medium">{p.nombre}</p><p className="text-sm text-muted-foreground">{p.especie} · {p.raza || 'Sin raza'}</p></div></div><Badge variant="outline">{p.estado}</Badge></div>) : <p className="text-sm text-muted-foreground">No hay mascotas para mostrar.</p>}</CardContent></Card></Shell> }

export function VeterinarianUsers() { const [users, setUsers] = useState<UserRecord[]>([]); const [error, setError] = useState(''); useEffect(() => { veterinarioApi.usuarios().then(data => setUsers(asItems<UserRecord>(data))).catch(e => setError(parseApiError(e))) }, []); return <Shell title="Usuarios" description="Consulta los propietarios asociados a las mascotas."><Card><CardContent className="flex flex-col gap-3 p-4"><ErrorMessage error={error} />{users.length ? users.map(u => <div key={u.id} className="flex items-center gap-3 rounded-lg border p-4"><Users className="text-primary" /><div><p className="font-medium">{u.nombre}</p><p className="text-sm text-muted-foreground">{u.email}</p></div></div>) : <p className="text-sm text-muted-foreground">No hay usuarios disponibles.</p>}</CardContent></Card></Shell> }

export function ClinicalHistories() { const [items, setItems] = useState<HistoriaClinica[]>([]); const [error, setError] = useState(''); useEffect(() => { veterinarioApi.historias().then(setItems).catch(e => setError(parseApiError(e))) }, []); return <Shell title="Historias clínicas" description="Lista y consulta la evolución clínica de tus pacientes."><div className="flex justify-end"><Link href="/dashboard/veterinario/historias-clinicas/nueva"><Button><Plus data-icon="inline-start" />Nueva historia</Button></Link></div><Card><CardContent className="flex flex-col gap-3 p-4"><ErrorMessage error={error} />{items.length ? items.map(h => <Link href={`/dashboard/veterinario/historias-clinicas/${h.id}`} key={h.id} className="rounded-lg border p-4 hover:bg-muted/50"><div className="flex items-center justify-between gap-3"><p className="font-medium">{h.motivo_consulta}</p><Badge variant="outline">{formatDateOnly(h.fecha_consulta)}</Badge></div><p className="mt-1 text-sm text-muted-foreground">Mascota: {h.mascota_id}</p></Link>) : <p className="text-sm text-muted-foreground">No hay historias clínicas registradas.</p>}</CardContent></Card></Shell> }

export function NewClinicalHistory() { const [form, setForm] = useState({ mascota_id: '', motivo_consulta: '', diagnostico: '', tratamiento: '', peso_kg: '', temperatura_c: '' }); const [error, setError] = useState(''); const [saving, setSaving] = useState(false); const submit = async (e: FormEvent) => { e.preventDefault(); setSaving(true); try { const h = await veterinarioApi.crearHistoria({ ...form, peso_kg: form.peso_kg ? Number(form.peso_kg) : undefined, temperatura_c: form.temperatura_c ? Number(form.temperatura_c) : undefined }); location.href = `/dashboard/veterinario/historias-clinicas/${h.id}` } catch (e) { setError(parseApiError(e)) } finally { setSaving(false) } }; return <Shell title="Nueva historia clínica" description="Registra una consulta con validación en el backend."><Card><CardContent className="p-4 sm:p-6"><form onSubmit={submit} className="grid gap-4 md:grid-cols-2"><Field label="ID de mascota"><Input required value={form.mascota_id} onChange={e => setForm({ ...form, mascota_id: e.target.value })} /></Field><Field label="Motivo de consulta"><Input required value={form.motivo_consulta} onChange={e => setForm({ ...form, motivo_consulta: e.target.value })} /></Field><Field label="Diagnóstico"><Input value={form.diagnostico} onChange={e => setForm({ ...form, diagnostico: e.target.value })} /></Field><Field label="Tratamiento"><Input value={form.tratamiento} onChange={e => setForm({ ...form, tratamiento: e.target.value })} /></Field><Field label="Peso (kg)"><Input type="number" min="0" step="0.1" value={form.peso_kg} onChange={e => setForm({ ...form, peso_kg: e.target.value })} /></Field><Field label="Temperatura (°C)"><Input type="number" min="30" max="45" step="0.1" value={form.temperatura_c} onChange={e => setForm({ ...form, temperatura_c: e.target.value })} /></Field><ErrorMessage error={error} /><Button disabled={saving} type="submit">{saving ? 'Guardando…' : 'Guardar historia'}</Button></form></CardContent></Card></Shell> }

export function ClinicalHistoryDetail({ id }: { id: string }) { const [item, setItem] = useState<HistoriaClinica | null>(null); const [error, setError] = useState(''); useEffect(() => { veterinarioApi.historia(id).then(setItem).catch(e => setError(parseApiError(e))) }, [id]); return <Shell title="Historia clínica" description="Detalle de la consulta y sus valores clínicos."><Card><CardContent className="flex flex-col gap-4 p-4 sm:p-6"><ErrorMessage error={error} />{item && <><div className="flex items-center justify-between gap-3"><Badge>{formatDateOnly(item.fecha_consulta)}</Badge><span className="text-sm text-muted-foreground">Mascota: {item.mascota_id}</span></div><Detail label="Motivo" value={item.motivo_consulta} /><Detail label="Diagnóstico" value={item.diagnostico} /><Detail label="Tratamiento" value={item.tratamiento} /><Detail label="Peso" value={item.peso_kg ? `${item.peso_kg} kg` : '—'} /><Detail label="Temperatura" value={item.temperatura_c ? `${item.temperatura_c} °C` : '—'} /></>}</CardContent></Card></Shell> }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div className="flex flex-col gap-2"><Label>{label}</Label>{children}</div> }
function Detail({ label, value }: { label: string; value?: string | null }) { return <div className="border-b pb-3"><p className="text-xs font-medium uppercase text-muted-foreground">{label}</p><p className="mt-1 leading-6">{value || '—'}</p></div> }
